export const ADMIT_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const GOODS_ROUTE = '/goods'
export const HOME_ROUTE = '/home'